version: '2'
services:
    puigthesong-app:
        image: puigthesong
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://puigthesong-mysql:3306/puigthesong?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    puigthesong-mysql:
        extends:
            file: mysql.yml
            service: puigthesong-mysql
